### ISSUE TITLE
fard only working for holder of card

### ISSUE THREAD

**Issue by TB4T3M4N** [Orangenal-name/CoolRoundsModLol#2]
![image_2022-09-30_203136655](https://user-images.githubusercontent.com/70405748/193385773-7c50c60e-0bdd-4203-83c0-3aa99bc763a1.png)

cant hear both pewpew and fard, only the one who grabs the card can hear it

**Comment by TB4T3M4N** [comment]
image is to show what mods we have

**Comment by TB4T3M4N** [comment]
made sure volume is at one

**Comment by TB4T3M4N** [comment]
one opponent shoots can only hear from left ear, i shoot I only hear out of right ear very quitly

**Comment by Orangenal-name** [comment]
Hi, does this still happen?
